spring:
  application:
    name: DinosaurStore-auth
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.48.192:8848

#    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: localhost:8080

  redis:
    host: 124.222.48.192
    port: 6379
    password: 123456
  session:
    store-type:
      redis
  thymeleaf:
    cache: false

##开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true

##暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


server:
  port: 20000
  servlet:
    session:
      timeout: 30m


