server:
  port: 40000


spring:
  application:
    name: DinosaurStore-cart

  cloud:
    nacos:
      discovery:
        server-addr: 124.222.48.192:8848

#    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: localhost:8080

  redis:
    port: 6379
    host: 124.222.48.192
    password: 123456

##开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true

  session:
    store-type: redis

#配置线程池
store:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10


##暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
logging:
  level:
    com.jcwang: debug

